version: '3.8'
services:
  db:
    # Par exemple, si vous souhaitez customiser l'image de MariaDB,
    # vous pouvez créer un dossier "db" contenant un Dockerfile qui part de l'image officielle.
    build:
      context: ./db
      dockerfile: Dockerfile
    image: harbor.korporate.org/mywp/mariadb:1
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    # Dans le cas de Wordpress, si vous souhaitez y apporter des modifications,
    # créez un dossier "wordpress" avec votre Dockerfile personnalisé.
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image:  harbor.korporate.org/mywp/wordpress:1
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

volumes:
  db_data: