apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
