apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: ftp
  name: ftp
spec:
  ports:
    - name: "21"
      port: 21
      targetPort: 21
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "5002"
      port: 5002
      targetPort: 5002
    - name: "5003"
      port: 5003
      targetPort: 5003
    - name: "5004"
      port: 5004
      targetPort: 5004
    - name: "5005"
      port: 5005
      targetPort: 5005
    - name: "5006"
      port: 5006
      targetPort: 5006
    - name: "5007"
      port: 5007
      targetPort: 5007
    - name: "5008"
      port: 5008
      targetPort: 5008
    - name: "5009"
      port: 5009
      targetPort: 5009
    - name: "5010"
      port: 5010
      targetPort: 5010
    - name: "5011"
      port: 5011
      targetPort: 5011
    - name: "5012"
      port: 5012
      targetPort: 5012
    - name: "5013"
      port: 5013
      targetPort: 5013
    - name: "5014"
      port: 5014
      targetPort: 5014
    - name: "5015"
      port: 5015
      targetPort: 5015
    - name: "5016"
      port: 5016
      targetPort: 5016
    - name: "5017"
      port: 5017
      targetPort: 5017
    - name: "5018"
      port: 5018
      targetPort: 5018
    - name: "5019"
      port: 5019
      targetPort: 5019
    - name: "5020"
      port: 5020
      targetPort: 5020
  selector:
    io.kompose.service: ftp
