apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: DOMAIN_NAME
              value: korporate.org
          image: nginx
          name: nginx
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/wp
              name: wordpress
            - mountPath: /var/www/html/revshells
              name: revshells
            - mountPath: /var/www/html/adminer
              name: adminer
            - mountPath: /certs
              name: certs
      restartPolicy: Always
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
        - name: revshells
          persistentVolumeClaim:
            claimName: revshells
        - name: adminer
          persistentVolumeClaim:
            claimName: adminer
        - name: certs
          persistentVolumeClaim:
            claimName: certs
