apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: revshells
  name: revshells
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
