apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: uptime-kuma
    spec:
      containers:
        - env:
            - name: DOMAIN_NAME
              value: korporate.org
            - name: UK_PASSWORD
              value: evilKuma
            - name: UK_SITE_NAME
              value: daribeir's inception website
            - name: UK_SITE_URL
              value: https://korporate.org
            - name: UK_USER
              value: daribeir
          image: uptime-kuma
          name: uptime-kuma
          volumeMounts:
            - mountPath: /uptime-kuma/data
              name: uptime-kuma
      restartPolicy: Always
      volumes:
        - name: uptime-kuma
          persistentVolumeClaim:
            claimName: uptime-kuma
